// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: rpctransact.proto

package rpctransact // import "github.com/hyperledger/burrow/rpc/rpctransact"

import proto "github.com/gogo/protobuf/proto"
import golang_proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/golang/protobuf/ptypes/duration"
import exec "github.com/hyperledger/burrow/execution/exec"
import txs "github.com/hyperledger/burrow/txs"
import payload "github.com/hyperledger/burrow/txs/payload"

import github_com_hyperledger_burrow_crypto "github.com/hyperledger/burrow/crypto"
import github_com_hyperledger_burrow_txs "github.com/hyperledger/burrow/txs"
import time "time"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

import github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = golang_proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type CallCodeParam struct {
	FromAddress          github_com_hyperledger_burrow_crypto.Address `protobuf:"bytes,1,opt,name=FromAddress,proto3,customtype=github.com/hyperledger/burrow/crypto.Address" json:"FromAddress"`
	Code                 []byte                                       `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	Data                 []byte                                       `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *CallCodeParam) Reset()         { *m = CallCodeParam{} }
func (m *CallCodeParam) String() string { return proto.CompactTextString(m) }
func (*CallCodeParam) ProtoMessage()    {}
func (*CallCodeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpctransact_2252056cec4ada40, []int{0}
}
func (m *CallCodeParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CallCodeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CallCodeParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *CallCodeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallCodeParam.Merge(dst, src)
}
func (m *CallCodeParam) XXX_Size() int {
	return m.Size()
}
func (m *CallCodeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_CallCodeParam.DiscardUnknown(m)
}

var xxx_messageInfo_CallCodeParam proto.InternalMessageInfo

func (m *CallCodeParam) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CallCodeParam) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (*CallCodeParam) XXX_MessageName() string {
	return "rpctransact.CallCodeParam"
}

type TxEnvelope struct {
	Envelope             *github_com_hyperledger_burrow_txs.Envelope `protobuf:"bytes,1,opt,name=Envelope,customtype=github.com/hyperledger/burrow/txs.Envelope" json:"Envelope,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                    `json:"-"`
	XXX_unrecognized     []byte                                      `json:"-"`
	XXX_sizecache        int32                                       `json:"-"`
}

func (m *TxEnvelope) Reset()         { *m = TxEnvelope{} }
func (m *TxEnvelope) String() string { return proto.CompactTextString(m) }
func (*TxEnvelope) ProtoMessage()    {}
func (*TxEnvelope) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpctransact_2252056cec4ada40, []int{1}
}
func (m *TxEnvelope) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxEnvelope) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxEnvelope.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TxEnvelope) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxEnvelope.Merge(dst, src)
}
func (m *TxEnvelope) XXX_Size() int {
	return m.Size()
}
func (m *TxEnvelope) XXX_DiscardUnknown() {
	xxx_messageInfo_TxEnvelope.DiscardUnknown(m)
}

var xxx_messageInfo_TxEnvelope proto.InternalMessageInfo

func (*TxEnvelope) XXX_MessageName() string {
	return "rpctransact.TxEnvelope"
}

// For Batch transactions
type TxEnvelopeBatchParam struct {
	Envelope             []github_com_hyperledger_burrow_txs.Envelope `protobuf:"bytes,1,rep,name=Envelope,customtype=github.com/hyperledger/burrow/txs.Envelope" json:"Envelope"`
	Timeout              time.Duration                                `protobuf:"bytes,2,opt,name=Timeout,stdduration" json:"Timeout"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *TxEnvelopeBatchParam) Reset()         { *m = TxEnvelopeBatchParam{} }
func (m *TxEnvelopeBatchParam) String() string { return proto.CompactTextString(m) }
func (*TxEnvelopeBatchParam) ProtoMessage()    {}
func (*TxEnvelopeBatchParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpctransact_2252056cec4ada40, []int{2}
}
func (m *TxEnvelopeBatchParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxEnvelopeBatchParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxEnvelopeBatchParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TxEnvelopeBatchParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxEnvelopeBatchParam.Merge(dst, src)
}
func (m *TxEnvelopeBatchParam) XXX_Size() int {
	return m.Size()
}
func (m *TxEnvelopeBatchParam) XXX_DiscardUnknown() {
	xxx_messageInfo_TxEnvelopeBatchParam.DiscardUnknown(m)
}

var xxx_messageInfo_TxEnvelopeBatchParam proto.InternalMessageInfo

func (m *TxEnvelopeBatchParam) GetTimeout() time.Duration {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (*TxEnvelopeBatchParam) XXX_MessageName() string {
	return "rpctransact.TxEnvelopeBatchParam"
}

type ReceiptBatch struct {
	Receipts             []*txs.Receipt `protobuf:"bytes,1,rep,name=Receipts" json:"Receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReceiptBatch) Reset()         { *m = ReceiptBatch{} }
func (m *ReceiptBatch) String() string { return proto.CompactTextString(m) }
func (*ReceiptBatch) ProtoMessage()    {}
func (*ReceiptBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpctransact_2252056cec4ada40, []int{3}
}
func (m *ReceiptBatch) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ReceiptBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ReceiptBatch.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *ReceiptBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiptBatch.Merge(dst, src)
}
func (m *ReceiptBatch) XXX_Size() int {
	return m.Size()
}
func (m *ReceiptBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiptBatch.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiptBatch proto.InternalMessageInfo

func (m *ReceiptBatch) GetReceipts() []*txs.Receipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func (*ReceiptBatch) XXX_MessageName() string {
	return "rpctransact.ReceiptBatch"
}

type TxEnvelopeParam struct {
	// An existing Envelope - either signed or unsigned - if the latter will be signed server-side
	Envelope *github_com_hyperledger_burrow_txs.Envelope `protobuf:"bytes,1,opt,name=Envelope,customtype=github.com/hyperledger/burrow/txs.Envelope" json:"Envelope,omitempty"`
	// If no Envelope provided then one will be generated from the provided payload and signed server-side
	Payload *payload.Any `protobuf:"bytes,2,opt,name=Payload" json:"Payload,omitempty"`
	// The amount of time to wait for the transaction to be committed and the TxExecution to be returned (server-side).
	// If zero there wait is unbounded. Timed out transactions return SyncInfo state that may be helpful debugging
	// non-committed transactions - this timeout must be less than client timeout to see such information!
	Timeout              time.Duration `protobuf:"bytes,3,opt,name=Timeout,stdduration" json:"Timeout"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TxEnvelopeParam) Reset()         { *m = TxEnvelopeParam{} }
func (m *TxEnvelopeParam) String() string { return proto.CompactTextString(m) }
func (*TxEnvelopeParam) ProtoMessage()    {}
func (*TxEnvelopeParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_rpctransact_2252056cec4ada40, []int{4}
}
func (m *TxEnvelopeParam) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxEnvelopeParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxEnvelopeParam.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TxEnvelopeParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxEnvelopeParam.Merge(dst, src)
}
func (m *TxEnvelopeParam) XXX_Size() int {
	return m.Size()
}
func (m *TxEnvelopeParam) XXX_DiscardUnknown() {
	xxx_messageInfo_TxEnvelopeParam.DiscardUnknown(m)
}

var xxx_messageInfo_TxEnvelopeParam proto.InternalMessageInfo

func (m *TxEnvelopeParam) GetPayload() *payload.Any {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TxEnvelopeParam) GetTimeout() time.Duration {
	if m != nil {
		return m.Timeout
	}
	return 0
}

func (*TxEnvelopeParam) XXX_MessageName() string {
	return "rpctransact.TxEnvelopeParam"
}
func init() {
	proto.RegisterType((*CallCodeParam)(nil), "rpctransact.CallCodeParam")
	golang_proto.RegisterType((*CallCodeParam)(nil), "rpctransact.CallCodeParam")
	proto.RegisterType((*TxEnvelope)(nil), "rpctransact.TxEnvelope")
	golang_proto.RegisterType((*TxEnvelope)(nil), "rpctransact.TxEnvelope")
	proto.RegisterType((*TxEnvelopeBatchParam)(nil), "rpctransact.TxEnvelopeBatchParam")
	golang_proto.RegisterType((*TxEnvelopeBatchParam)(nil), "rpctransact.TxEnvelopeBatchParam")
	proto.RegisterType((*ReceiptBatch)(nil), "rpctransact.ReceiptBatch")
	golang_proto.RegisterType((*ReceiptBatch)(nil), "rpctransact.ReceiptBatch")
	proto.RegisterType((*TxEnvelopeParam)(nil), "rpctransact.TxEnvelopeParam")
	golang_proto.RegisterType((*TxEnvelopeParam)(nil), "rpctransact.TxEnvelopeParam")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TransactClient is the client API for Transact service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TransactClient interface {
	// Broadcast a transaction to the mempool - if the transaction is not signed signing will be attempted server-side
	// and wait for it to be included in block
	BroadcastTxSync(ctx context.Context, in *TxEnvelopeParam, opts ...grpc.CallOption) (*exec.TxExecution, error)
	// Broadcast a transaction to the mempool - if the transaction is not signed signing will be attempted server-side
	BroadcastTxAsync(ctx context.Context, in *TxEnvelopeParam, opts ...grpc.CallOption) (*txs.Receipt, error)
	// Batch send and receive
	BroadcastBatchAsync(ctx context.Context, in *TxEnvelopeBatchParam, opts ...grpc.CallOption) (*ReceiptBatch, error)
	// Sign transaction server-side
	SignTx(ctx context.Context, in *TxEnvelopeParam, opts ...grpc.CallOption) (*TxEnvelope, error)
	// Formulate a transaction from a Payload and retrun the envelop with the Tx bytes ready to sign
	FormulateTx(ctx context.Context, in *payload.Any, opts ...grpc.CallOption) (*TxEnvelope, error)
	// Formulate and sign a CallTx transaction signed server-side and wait for it to be included in a block, retrieving response
	CallTxSync(ctx context.Context, in *payload.CallTx, opts ...grpc.CallOption) (*exec.TxExecution, error)
	// Formulate and sign a CallTx transaction signed server-side
	CallTxAsync(ctx context.Context, in *payload.CallTx, opts ...grpc.CallOption) (*txs.Receipt, error)
	// Perform a 'simulated' call of a contract against the current committed EVM state without any changes been saved
	// and wait for the transaction to be included in a block
	CallTxSim(ctx context.Context, in *payload.CallTx, opts ...grpc.CallOption) (*exec.TxExecution, error)
	// Perform a 'simulated' execution of provided code against the current committed EVM state without any changes been saved
	CallCodeSim(ctx context.Context, in *CallCodeParam, opts ...grpc.CallOption) (*exec.TxExecution, error)
	// Formulate a SendTx transaction signed server-side and wait for it to be included in a block, retrieving response
	SendTxSync(ctx context.Context, in *payload.SendTx, opts ...grpc.CallOption) (*exec.TxExecution, error)
	// Formulate and  SendTx transaction signed server-side
	SendTxAsync(ctx context.Context, in *payload.SendTx, opts ...grpc.CallOption) (*txs.Receipt, error)
	// Formualte a NameTx signed server-side and wait for it to be included in a block returning the registered name
	NameTxSync(ctx context.Context, in *payload.NameTx, opts ...grpc.CallOption) (*exec.TxExecution, error)
	// Formulate a NameTx signed server-side
	NameTxAsync(ctx context.Context, in *payload.NameTx, opts ...grpc.CallOption) (*txs.Receipt, error)
}

type transactClient struct {
	cc *grpc.ClientConn
}

func NewTransactClient(cc *grpc.ClientConn) TransactClient {
	return &transactClient{cc}
}

func (c *transactClient) BroadcastTxSync(ctx context.Context, in *TxEnvelopeParam, opts ...grpc.CallOption) (*exec.TxExecution, error) {
	out := new(exec.TxExecution)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/BroadcastTxSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) BroadcastTxAsync(ctx context.Context, in *TxEnvelopeParam, opts ...grpc.CallOption) (*txs.Receipt, error) {
	out := new(txs.Receipt)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/BroadcastTxAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) BroadcastBatchAsync(ctx context.Context, in *TxEnvelopeBatchParam, opts ...grpc.CallOption) (*ReceiptBatch, error) {
	out := new(ReceiptBatch)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/BroadcastBatchAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) SignTx(ctx context.Context, in *TxEnvelopeParam, opts ...grpc.CallOption) (*TxEnvelope, error) {
	out := new(TxEnvelope)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/SignTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) FormulateTx(ctx context.Context, in *payload.Any, opts ...grpc.CallOption) (*TxEnvelope, error) {
	out := new(TxEnvelope)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/FormulateTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) CallTxSync(ctx context.Context, in *payload.CallTx, opts ...grpc.CallOption) (*exec.TxExecution, error) {
	out := new(exec.TxExecution)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/CallTxSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) CallTxAsync(ctx context.Context, in *payload.CallTx, opts ...grpc.CallOption) (*txs.Receipt, error) {
	out := new(txs.Receipt)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/CallTxAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) CallTxSim(ctx context.Context, in *payload.CallTx, opts ...grpc.CallOption) (*exec.TxExecution, error) {
	out := new(exec.TxExecution)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/CallTxSim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) CallCodeSim(ctx context.Context, in *CallCodeParam, opts ...grpc.CallOption) (*exec.TxExecution, error) {
	out := new(exec.TxExecution)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/CallCodeSim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) SendTxSync(ctx context.Context, in *payload.SendTx, opts ...grpc.CallOption) (*exec.TxExecution, error) {
	out := new(exec.TxExecution)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/SendTxSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) SendTxAsync(ctx context.Context, in *payload.SendTx, opts ...grpc.CallOption) (*txs.Receipt, error) {
	out := new(txs.Receipt)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/SendTxAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) NameTxSync(ctx context.Context, in *payload.NameTx, opts ...grpc.CallOption) (*exec.TxExecution, error) {
	out := new(exec.TxExecution)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/NameTxSync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transactClient) NameTxAsync(ctx context.Context, in *payload.NameTx, opts ...grpc.CallOption) (*txs.Receipt, error) {
	out := new(txs.Receipt)
	err := c.cc.Invoke(ctx, "/rpctransact.Transact/NameTxAsync", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactServer is the server API for Transact service.
type TransactServer interface {
	// Broadcast a transaction to the mempool - if the transaction is not signed signing will be attempted server-side
	// and wait for it to be included in block
	BroadcastTxSync(context.Context, *TxEnvelopeParam) (*exec.TxExecution, error)
	// Broadcast a transaction to the mempool - if the transaction is not signed signing will be attempted server-side
	BroadcastTxAsync(context.Context, *TxEnvelopeParam) (*txs.Receipt, error)
	// Batch send and receive
	BroadcastBatchAsync(context.Context, *TxEnvelopeBatchParam) (*ReceiptBatch, error)
	// Sign transaction server-side
	SignTx(context.Context, *TxEnvelopeParam) (*TxEnvelope, error)
	// Formulate a transaction from a Payload and retrun the envelop with the Tx bytes ready to sign
	FormulateTx(context.Context, *payload.Any) (*TxEnvelope, error)
	// Formulate and sign a CallTx transaction signed server-side and wait for it to be included in a block, retrieving response
	CallTxSync(context.Context, *payload.CallTx) (*exec.TxExecution, error)
	// Formulate and sign a CallTx transaction signed server-side
	CallTxAsync(context.Context, *payload.CallTx) (*txs.Receipt, error)
	// Perform a 'simulated' call of a contract against the current committed EVM state without any changes been saved
	// and wait for the transaction to be included in a block
	CallTxSim(context.Context, *payload.CallTx) (*exec.TxExecution, error)
	// Perform a 'simulated' execution of provided code against the current committed EVM state without any changes been saved
	CallCodeSim(context.Context, *CallCodeParam) (*exec.TxExecution, error)
	// Formulate a SendTx transaction signed server-side and wait for it to be included in a block, retrieving response
	SendTxSync(context.Context, *payload.SendTx) (*exec.TxExecution, error)
	// Formulate and  SendTx transaction signed server-side
	SendTxAsync(context.Context, *payload.SendTx) (*txs.Receipt, error)
	// Formualte a NameTx signed server-side and wait for it to be included in a block returning the registered name
	NameTxSync(context.Context, *payload.NameTx) (*exec.TxExecution, error)
	// Formulate a NameTx signed server-side
	NameTxAsync(context.Context, *payload.NameTx) (*txs.Receipt, error)
}

func RegisterTransactServer(s *grpc.Server, srv TransactServer) {
	s.RegisterService(&_Transact_serviceDesc, srv)
}

func _Transact_BroadcastTxSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxEnvelopeParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).BroadcastTxSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/BroadcastTxSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).BroadcastTxSync(ctx, req.(*TxEnvelopeParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_BroadcastTxAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxEnvelopeParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).BroadcastTxAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/BroadcastTxAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).BroadcastTxAsync(ctx, req.(*TxEnvelopeParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_BroadcastBatchAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxEnvelopeBatchParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).BroadcastBatchAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/BroadcastBatchAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).BroadcastBatchAsync(ctx, req.(*TxEnvelopeBatchParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_SignTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TxEnvelopeParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).SignTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/SignTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).SignTx(ctx, req.(*TxEnvelopeParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_FormulateTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.Any)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).FormulateTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/FormulateTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).FormulateTx(ctx, req.(*payload.Any))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_CallTxSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.CallTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).CallTxSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/CallTxSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).CallTxSync(ctx, req.(*payload.CallTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_CallTxAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.CallTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).CallTxAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/CallTxAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).CallTxAsync(ctx, req.(*payload.CallTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_CallTxSim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.CallTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).CallTxSim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/CallTxSim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).CallTxSim(ctx, req.(*payload.CallTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_CallCodeSim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallCodeParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).CallCodeSim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/CallCodeSim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).CallCodeSim(ctx, req.(*CallCodeParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_SendTxSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.SendTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).SendTxSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/SendTxSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).SendTxSync(ctx, req.(*payload.SendTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_SendTxAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.SendTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).SendTxAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/SendTxAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).SendTxAsync(ctx, req.(*payload.SendTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_NameTxSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.NameTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).NameTxSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/NameTxSync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).NameTxSync(ctx, req.(*payload.NameTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transact_NameTxAsync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(payload.NameTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactServer).NameTxAsync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpctransact.Transact/NameTxAsync",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactServer).NameTxAsync(ctx, req.(*payload.NameTx))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transact_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpctransact.Transact",
	HandlerType: (*TransactServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BroadcastTxSync",
			Handler:    _Transact_BroadcastTxSync_Handler,
		},
		{
			MethodName: "BroadcastTxAsync",
			Handler:    _Transact_BroadcastTxAsync_Handler,
		},
		{
			MethodName: "BroadcastBatchAsync",
			Handler:    _Transact_BroadcastBatchAsync_Handler,
		},
		{
			MethodName: "SignTx",
			Handler:    _Transact_SignTx_Handler,
		},
		{
			MethodName: "FormulateTx",
			Handler:    _Transact_FormulateTx_Handler,
		},
		{
			MethodName: "CallTxSync",
			Handler:    _Transact_CallTxSync_Handler,
		},
		{
			MethodName: "CallTxAsync",
			Handler:    _Transact_CallTxAsync_Handler,
		},
		{
			MethodName: "CallTxSim",
			Handler:    _Transact_CallTxSim_Handler,
		},
		{
			MethodName: "CallCodeSim",
			Handler:    _Transact_CallCodeSim_Handler,
		},
		{
			MethodName: "SendTxSync",
			Handler:    _Transact_SendTxSync_Handler,
		},
		{
			MethodName: "SendTxAsync",
			Handler:    _Transact_SendTxAsync_Handler,
		},
		{
			MethodName: "NameTxSync",
			Handler:    _Transact_NameTxSync_Handler,
		},
		{
			MethodName: "NameTxAsync",
			Handler:    _Transact_NameTxAsync_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpctransact.proto",
}

func (m *CallCodeParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallCodeParam) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	dAtA[i] = 0xa
	i++
	i = encodeVarintRpctransact(dAtA, i, uint64(m.FromAddress.Size()))
	n1, err := m.FromAddress.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n1
	if len(m.Code) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintRpctransact(dAtA, i, uint64(len(m.Code)))
		i += copy(dAtA[i:], m.Code)
	}
	if len(m.Data) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintRpctransact(dAtA, i, uint64(len(m.Data)))
		i += copy(dAtA[i:], m.Data)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TxEnvelope) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxEnvelope) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Envelope != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRpctransact(dAtA, i, uint64(m.Envelope.Size()))
		n2, err := m.Envelope.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n2
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TxEnvelopeBatchParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxEnvelopeBatchParam) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Envelope) > 0 {
		for _, msg := range m.Envelope {
			dAtA[i] = 0xa
			i++
			i = encodeVarintRpctransact(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintRpctransact(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdDuration(m.Timeout)))
	n3, err := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.Timeout, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *ReceiptBatch) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ReceiptBatch) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Receipts) > 0 {
		for _, msg := range m.Receipts {
			dAtA[i] = 0xa
			i++
			i = encodeVarintRpctransact(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TxEnvelopeParam) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxEnvelopeParam) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Envelope != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintRpctransact(dAtA, i, uint64(m.Envelope.Size()))
		n4, err := m.Envelope.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n4
	}
	if m.Payload != nil {
		dAtA[i] = 0x12
		i++
		i = encodeVarintRpctransact(dAtA, i, uint64(m.Payload.Size()))
		n5, err := m.Payload.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n5
	}
	dAtA[i] = 0x1a
	i++
	i = encodeVarintRpctransact(dAtA, i, uint64(github_com_gogo_protobuf_types.SizeOfStdDuration(m.Timeout)))
	n6, err := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.Timeout, dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n6
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintRpctransact(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *CallCodeParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.FromAddress.Size()
	n += 1 + l + sovRpctransact(uint64(l))
	l = len(m.Code)
	if l > 0 {
		n += 1 + l + sovRpctransact(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovRpctransact(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TxEnvelope) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Envelope != nil {
		l = m.Envelope.Size()
		n += 1 + l + sovRpctransact(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TxEnvelopeBatchParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Envelope) > 0 {
		for _, e := range m.Envelope {
			l = e.Size()
			n += 1 + l + sovRpctransact(uint64(l))
		}
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.Timeout)
	n += 1 + l + sovRpctransact(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ReceiptBatch) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Receipts) > 0 {
		for _, e := range m.Receipts {
			l = e.Size()
			n += 1 + l + sovRpctransact(uint64(l))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TxEnvelopeParam) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Envelope != nil {
		l = m.Envelope.Size()
		n += 1 + l + sovRpctransact(uint64(l))
	}
	if m.Payload != nil {
		l = m.Payload.Size()
		n += 1 + l + sovRpctransact(uint64(l))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.Timeout)
	n += 1 + l + sovRpctransact(uint64(l))
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovRpctransact(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozRpctransact(x uint64) (n int) {
	return sovRpctransact(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CallCodeParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpctransact
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallCodeParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallCodeParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FromAddress.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Code = append(m.Code[:0], dAtA[iNdEx:postIndex]...)
			if m.Code == nil {
				m.Code = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpctransact(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpctransact
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxEnvelope) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpctransact
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxEnvelope: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxEnvelope: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Envelope", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Envelope == nil {
				m.Envelope = &github_com_hyperledger_burrow_txs.Envelope{}
			}
			if err := m.Envelope.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpctransact(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpctransact
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxEnvelopeBatchParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpctransact
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxEnvelopeBatchParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxEnvelopeBatchParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Envelope", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Envelope = append(m.Envelope, github_com_hyperledger_burrow_txs.Envelope{})
			if err := m.Envelope[len(m.Envelope)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.Timeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpctransact(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpctransact
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ReceiptBatch) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpctransact
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ReceiptBatch: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ReceiptBatch: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receipts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receipts = append(m.Receipts, &txs.Receipt{})
			if err := m.Receipts[len(m.Receipts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpctransact(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpctransact
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxEnvelopeParam) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRpctransact
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxEnvelopeParam: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxEnvelopeParam: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Envelope", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Envelope == nil {
				m.Envelope = &github_com_hyperledger_burrow_txs.Envelope{}
			}
			if err := m.Envelope.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Payload == nil {
				m.Payload = &payload.Any{}
			}
			if err := m.Payload.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timeout", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthRpctransact
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.Timeout, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRpctransact(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthRpctransact
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRpctransact(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRpctransact
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRpctransact
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthRpctransact
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowRpctransact
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipRpctransact(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthRpctransact = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRpctransact   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("rpctransact.proto", fileDescriptor_rpctransact_2252056cec4ada40) }
func init() {
	golang_proto.RegisterFile("rpctransact.proto", fileDescriptor_rpctransact_2252056cec4ada40)
}

var fileDescriptor_rpctransact_2252056cec4ada40 = []byte{
	// 632 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xfe, 0xf9, 0x57, 0x68, 0xd3, 0x71, 0xaa, 0xd2, 0x05, 0x89, 0x36, 0x42, 0x0e, 0xe4, 0x80,
	0x2a, 0xd4, 0xda, 0x55, 0xe8, 0x81, 0x03, 0x7f, 0x54, 0xf7, 0xcf, 0x11, 0x55, 0x8e, 0x85, 0x04,
	0x12, 0x87, 0x8d, 0xbd, 0xb8, 0x96, 0x6c, 0xaf, 0xb5, 0x5e, 0x83, 0xf3, 0x14, 0x5c, 0x79, 0x10,
	0x1e, 0x80, 0x63, 0x8f, 0x48, 0xdc, 0x7a, 0x28, 0xa8, 0x3d, 0xf1, 0x16, 0xc8, 0xbb, 0xeb, 0xc4,
	0x6e, 0x9a, 0x16, 0x90, 0xb8, 0xcd, 0xce, 0xec, 0xf7, 0xcd, 0xcc, 0x37, 0x3b, 0x0b, 0x2b, 0x2c,
	0xf5, 0x38, 0xc3, 0x49, 0x86, 0x3d, 0x6e, 0xa6, 0x8c, 0x72, 0x8a, 0xf4, 0x9a, 0xab, 0xb3, 0x19,
	0x84, 0xfc, 0x28, 0x1f, 0x9a, 0x1e, 0x8d, 0xad, 0x80, 0x06, 0xd4, 0x12, 0x77, 0x86, 0xf9, 0x3b,
	0x71, 0x12, 0x07, 0x61, 0x49, 0x6c, 0xc7, 0x08, 0x28, 0x0d, 0x22, 0x32, 0xb9, 0xe5, 0xe7, 0x0c,
	0xf3, 0x90, 0x26, 0x2a, 0x0e, 0xa4, 0x20, 0x9e, 0xb2, 0x97, 0x52, 0x3c, 0x8a, 0x28, 0xf6, 0xd5,
	0x71, 0x91, 0x17, 0x99, 0x34, 0x7b, 0x1f, 0x35, 0x58, 0xda, 0xc5, 0x51, 0xb4, 0x4b, 0x7d, 0x72,
	0x88, 0x19, 0x8e, 0xd1, 0x2b, 0xd0, 0x0f, 0x18, 0x8d, 0x77, 0x7c, 0x9f, 0x91, 0x2c, 0x5b, 0xd5,
	0xee, 0x6b, 0xeb, 0x6d, 0x7b, 0xfb, 0xf8, 0xb4, 0xfb, 0xdf, 0xc9, 0x69, 0x77, 0xa3, 0x56, 0xe3,
	0xd1, 0x28, 0x25, 0x2c, 0x22, 0x7e, 0x40, 0x98, 0x35, 0xcc, 0x19, 0xa3, 0x1f, 0x2c, 0x8f, 0x8d,
	0x52, 0x4e, 0x4d, 0x85, 0x75, 0xea, 0x44, 0x08, 0xc1, 0x8d, 0x32, 0xc9, 0xea, 0xff, 0x25, 0xa1,
	0x23, 0xec, 0xd2, 0xb7, 0x87, 0x39, 0x5e, 0x9d, 0x93, 0xbe, 0xd2, 0xee, 0x05, 0x00, 0x6e, 0xb1,
	0x9f, 0xbc, 0x27, 0x11, 0x4d, 0x09, 0x7a, 0x0d, 0xad, 0xca, 0x16, 0xa5, 0xe8, 0xfd, 0x25, 0xb3,
	0xac, 0xbe, 0x72, 0xda, 0xe6, 0xc9, 0x69, 0xf7, 0xd1, 0xd5, 0x55, 0xd5, 0xef, 0x3b, 0x63, 0xba,
	0xde, 0x67, 0x0d, 0xee, 0x4c, 0x32, 0xd9, 0x98, 0x7b, 0x47, 0x52, 0x81, 0xb7, 0x8d, 0x9c, 0x73,
	0xd3, 0x39, 0xfb, 0x4a, 0x8d, 0xbf, 0xca, 0x8b, 0x9e, 0xc1, 0x82, 0x1b, 0xc6, 0x84, 0xe6, 0x5c,
	0x68, 0xa1, 0xf7, 0xd7, 0x4c, 0x39, 0x4a, 0xb3, 0x1a, 0xa5, 0xb9, 0xa7, 0x46, 0x69, 0xb7, 0xca,
	0x4c, 0x9f, 0xbe, 0x77, 0x35, 0xa7, 0xc2, 0xf4, 0x9e, 0x40, 0xdb, 0x21, 0x1e, 0x09, 0x53, 0x2e,
	0x4a, 0x46, 0xeb, 0xd0, 0x52, 0xe7, 0x4c, 0x55, 0xdb, 0x16, 0xd5, 0x2a, 0xa7, 0x33, 0x8e, 0xf6,
	0xbe, 0x69, 0xb0, 0x3c, 0x69, 0x58, 0xf6, 0xfa, 0xef, 0xf4, 0x45, 0x0f, 0x61, 0xe1, 0x50, 0x3e,
	0x3b, 0xd5, 0x67, 0xdb, 0xac, 0x9e, 0xe1, 0x4e, 0x32, 0x72, 0xaa, 0x60, 0x5d, 0x8f, 0xb9, 0x3f,
	0xd7, 0xa3, 0xff, 0xf3, 0x26, 0xb4, 0x5c, 0xb5, 0x43, 0xc8, 0x86, 0x65, 0x9b, 0x51, 0xec, 0x7b,
	0x38, 0xe3, 0x6e, 0x31, 0x18, 0x25, 0x1e, 0xba, 0x67, 0xd6, 0xf7, 0xee, 0x42, 0xff, 0x9d, 0x15,
	0x53, 0xac, 0x89, 0x5b, 0xec, 0x17, 0xc4, 0xcb, 0xcb, 0x1c, 0xe8, 0x39, 0xdc, 0xaa, 0x71, 0xec,
	0x64, 0xd7, 0x93, 0x34, 0x04, 0x47, 0x03, 0xb8, 0x3d, 0xc6, 0x8b, 0x11, 0x49, 0x8a, 0x07, 0x33,
	0x28, 0x26, 0x0f, 0xaf, 0xb3, 0xd6, 0xb8, 0xd2, 0x98, 0xf2, 0x0b, 0x98, 0x1f, 0x84, 0x41, 0xe2,
	0x16, 0xd7, 0x94, 0x72, 0x77, 0x46, 0x14, 0x6d, 0x83, 0x7e, 0x40, 0x59, 0x9c, 0x47, 0x98, 0x13,
	0xb7, 0x40, 0x8d, 0x59, 0xcc, 0x46, 0x6d, 0x01, 0x94, 0xbf, 0x83, 0x92, 0x72, 0x79, 0x0c, 0x92,
	0xce, 0xcb, 0xd4, 0xdb, 0x00, 0x5d, 0x06, 0x65, 0xd7, 0x53, 0x90, 0xa6, 0x56, 0x16, 0x2c, 0x2a,
	0xfe, 0x30, 0xfe, 0x2d, 0xfa, 0xa7, 0x92, 0xbe, 0xfc, 0x3d, 0x4a, 0x48, 0xa7, 0x51, 0x78, 0xe3,
	0x23, 0xbb, 0x0c, 0xbd, 0x05, 0x30, 0x20, 0x89, 0x3f, 0xd5, 0x8e, 0x74, 0xce, 0x68, 0x47, 0x06,
	0x2f, 0xb6, 0xa3, 0x20, 0xcd, 0x76, 0xb6, 0x00, 0x5e, 0xe2, 0x98, 0x4c, 0xf1, 0x4b, 0xe7, 0x0c,
	0x7e, 0x19, 0xbc, 0xc8, 0xaf, 0x20, 0x0d, 0x7e, 0x7b, 0xf7, 0xf8, 0xcc, 0xd0, 0xbe, 0x9e, 0x19,
	0xda, 0x8f, 0x33, 0x43, 0xfb, 0x72, 0x6e, 0x68, 0xc7, 0xe7, 0x86, 0xf6, 0x66, 0xf3, 0xea, 0xf5,
	0x64, 0xa9, 0x67, 0xd5, 0x54, 0x1a, 0xce, 0x8b, 0xb5, 0x7a, 0xfc, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0xf2, 0x06, 0x07, 0x95, 0x90, 0x06, 0x00, 0x00,
}
